"use client";

import { useState, useTransition } from "react";
import { generateInsights } from "@/app/actions/chronicle";
import { formatShortDate } from "@/lib/format";
import { clsx } from "@/lib/cx";

type Range = "30d" | "90d";
type Status = "idle" | "loading" | "ok" | "error";

// Minimal markdown → JSX renderer for Claude's response: handles #/##/###
// headings, **bold**, and "- " bullets — enough for the summary prompt's
// requested format without pulling in a markdown dependency.
function renderMarkdown(md: string): React.ReactNode {
  const lines = md.split("\n");
  return (
    <>
      {lines.map((line, i) => {
        if (line.startsWith("### ")) return <h3 key={i} className="text-sm font-extrabold text-text-dark mt-4 mb-1">{inline(line.slice(4))}</h3>;
        if (line.startsWith("## ")) return <h2 key={i} className="text-base font-extrabold text-text-dark mt-5 mb-1">{inline(line.slice(3))}</h2>;
        if (line.startsWith("# ")) return <h1 key={i} className="text-lg font-extrabold text-text-dark mt-5 mb-1">{inline(line.slice(2))}</h1>;
        if (line.startsWith("- ") || line.startsWith("* ")) return <li key={i} className="text-sm text-text-dark leading-relaxed ml-4 list-disc">{inline(line.slice(2))}</li>;
        if (line.trim() === "") return <div key={i} className="h-2" />;
        return <p key={i} className="text-sm text-text-dark leading-relaxed">{inline(line)}</p>;
      })}
    </>
  );
}

function inline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return <>{parts.map((part, i) => (part.startsWith("**") && part.endsWith("**") ? <strong key={i} className="font-bold">{part.slice(2, -2)}</strong> : part))}</>;
}

export function ChronicleInsights() {
  const [open, setOpen] = useState(false);
  const [range, setRange] = useState<Range>("30d");
  const [status, setStatus] = useState<Status>("idle");
  const [summary, setSummary] = useState<string | null>(null);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [pending, startTransition] = useTransition();

  function handleGenerate() {
    setStatus("loading");
    setError(null);
    startTransition(async () => {
      try {
        const result = await generateInsights(range);
        setSummary(result.summary);
        setGeneratedAt(result.generatedAt);
        setStatus("ok");
      } catch (err) {
        setStatus("error");
        setError(err instanceof Error ? err.message : "Failed to generate summary.");
      }
    });
  }

  async function handleCopy() {
    if (!summary) return;
    await navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function mailtoLink(): string {
    if (!summary) return "#";
    const rangeLabel = range === "30d" ? "last 30 days" : "last 90 days";
    const subject = encodeURIComponent(`Care summary — ${rangeLabel}`);
    const body = encodeURIComponent(`Hi,\n\nHere is an AI-generated summary of the care timeline for the ${rangeLabel}:\n\n${summary}\n\n---\nGenerated by Family Care`);
    return `mailto:?subject=${subject}&body=${body}`;
  }

  return (
    <div className="rounded-2xl bg-white shadow-[0_2px_10px_rgba(0,0,0,0.06)] overflow-hidden">
      <button type="button" onClick={() => setOpen((o) => !o)} className="w-full flex items-center justify-between px-4 py-3.5 text-left">
        <div className="flex items-center gap-2.5">
          <span className="flex items-center justify-center w-7 h-7 rounded-full bg-lavender-100">🤖</span>
          <span className="text-sm font-extrabold text-text-dark">AI Insights</span>
          <span className="text-xs font-semibold text-lavender-600 bg-lavender-50 rounded-full px-2 py-0.5">Beta</span>
        </div>
        <span className={clsx("text-text-mid transition-transform duration-200", open && "rotate-180")}>⌄</span>
      </button>

      {open && (
        <div className="border-t border-line px-4 pb-4 pt-3 space-y-3">
          <div className="flex gap-2">
            {(["30d", "90d"] as Range[]).map((r) => (
              <button
                key={r}
                type="button"
                onClick={() => { setRange(r); setStatus("idle"); setSummary(null); setError(null); }}
                className={clsx(
                  "rounded-full px-4 py-1.5 text-xs font-extrabold transition-all",
                  range === r ? "bg-lavender-600 text-white" : "bg-lavender-50 text-lavender-700",
                )}
              >
                {r === "30d" ? "Last 30 days" : "Last 90 days"}
              </button>
            ))}
          </div>

          {(status === "idle" || status === "error") && (
            <button
              type="button"
              onClick={handleGenerate}
              disabled={pending}
              className="w-full rounded-xl bg-lavender-600 text-white text-sm font-bold py-2.5 px-4 hover:bg-lavender-700 transition-all disabled:opacity-60"
            >
              {status === "error" ? "Try again" : "Generate summary"}
            </button>
          )}

          {status === "loading" && (
            <div className="flex flex-col items-center gap-2 py-4">
              <p className="text-xs text-text-mid font-semibold">Generating summary with AI…</p>
            </div>
          )}

          {status === "error" && error && (
            <div className="rounded-xl bg-red-50 border border-red-200 px-3 py-2.5">
              <p className="text-xs text-red-600 font-semibold">{error}</p>
            </div>
          )}

          {status === "ok" && summary && (
            <div className="space-y-3">
              <div className="rounded-xl bg-lavender-50 border border-lavender-100 px-4 py-3">
                {renderMarkdown(summary)}
              </div>

              {generatedAt && <p className="text-xs text-text-mid">Generated {formatShortDate(generatedAt.slice(0, 10))}</p>}

              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={handleCopy}
                  className={clsx(
                    "flex-1 rounded-xl py-2 text-xs font-bold border transition-all",
                    copied ? "bg-sage-50 border-sage-300 text-sage-700" : "bg-white border-line text-text-mid hover:border-lavender-300 hover:text-lavender-700",
                  )}
                >
                  {copied ? "Copied!" : "Copy"}
                </button>
                <a
                  href={mailtoLink()}
                  className="flex-1 flex items-center justify-center rounded-xl py-2 text-xs font-bold border border-line bg-white text-text-mid hover:border-lavender-300 hover:text-lavender-700 transition-all"
                >
                  Share by email
                </a>
              </div>

              <button
                type="button"
                onClick={handleGenerate}
                disabled={pending}
                className="w-full rounded-xl border border-line bg-white text-xs font-bold text-text-mid py-2 hover:border-lavender-300 hover:text-lavender-600 transition-all disabled:opacity-60"
              >
                Regenerate
              </button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
